spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn

spring.datasource.username=jyothsna
spring.datasource.password=Jyo@0612

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE